// <auto-generated />
using FirstAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirstAPI.Migrations
{
    [DbContext(typeof(FirstAPIContext))]
    partial class FirstAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FirstAPI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearPublished")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Harper Lee",
                            Description = "A classic book titled 'To Kill a Mockingbird'.",
                            Title = "To Kill a Mockingbird",
                            YearPublished = 2025
                        },
                        new
                        {
                            Id = 2,
                            Author = "George Orwell",
                            Description = "A classic book titled '1984'.",
                            Title = "1984",
                            YearPublished = 2026
                        },
                        new
                        {
                            Id = 3,
                            Author = "F. Scott Fitzgerald",
                            Description = "A classic book titled 'The Great Gatsby'.",
                            Title = "The Great Gatsby",
                            YearPublished = 2027
                        },
                        new
                        {
                            Id = 4,
                            Author = "Herman Melville",
                            Description = "A classic book titled 'Moby Dick'.",
                            Title = "Moby Dick",
                            YearPublished = 2028
                        },
                        new
                        {
                            Id = 5,
                            Author = "Jane Austen",
                            Description = "A classic book titled 'Pride and Prejudice'.",
                            Title = "Pride and Prejudice",
                            YearPublished = 2029
                        },
                        new
                        {
                            Id = 6,
                            Author = "Leo Tolstoy",
                            Description = "A classic book titled 'War and Peace'.",
                            Title = "War and Peace",
                            YearPublished = 2030
                        },
                        new
                        {
                            Id = 7,
                            Author = "J.D. Salinger",
                            Description = "A classic book titled 'The Catcher in the Rye'.",
                            Title = "The Catcher in the Rye",
                            YearPublished = 2031
                        },
                        new
                        {
                            Id = 8,
                            Author = "J.R.R. Tolkien",
                            Description = "A classic book titled 'The Hobbit'.",
                            Title = "The Hobbit",
                            YearPublished = 2032
                        },
                        new
                        {
                            Id = 9,
                            Author = "J.K. Rowling",
                            Description = "A classic book titled 'The Lord of the Rings'.",
                            Title = "The Lord of the Rings",
                            YearPublished = 2033
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
